# Generated by Django 2.1.2 on 2018-10-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSG', '0002_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommm',
            old_name='profile1',
            new_name='profiles',
        ),
    ]
