# Generated by Django 2.1.2 on 2018-10-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSG', '0006_auto_20181027_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
    ]
